"""
------------------------------------------------------------
Archivo      : config.py
Proyecto     : Sistema de Gestión de Inventarios
Descripción  : Configuración global de la aplicación.
Autor        : Luis Alfonso Rosero
Arquitectura : MVC
------------------------------------------------------------
"""
import sys
import os
# ==========================
# INFORMACIÓN DE LA APLICACIÓN
# ==========================
STOCK_MINIMO_DEFAULT = 0.0
CATEGORIA_DEFAULT = "SIN CATEGORIA"
APP_NAME = ...
APP_VERSION = ...
APP_AUTHOR = ...
APP_COMPANY = ...

# ==========================
# RUTAS DEL PROYECTO
# ==========================

BASE_DIR = "D:\\PromineralesFinal"
DATABASE_DIR =...
DATABASE_PATH = os.path.join(BASE_DIR, "database", "prominerales.db")
INPUT_DIR = ...
OUTPUT_DIR = ...
RUTA_ARCHIVO_EXCEL ="D:\\PromineralesFinal\\Inventarios_ 2026.xlsx"

# ==========================
# CONFIGURACIÓN DE LA INTERFAZ
# ==========================

WINDOW_TITLE = ...
WINDOW_WIDTH = ...
WINDOW_HEIGHT = ...
THEME = ...
COLOR_THEME = ...

# ==========================
# CONFIGURACIÓN DE LA BASE DE DATOS
# ==========================

DATABASE_NAME = ...
DATABASE_VERSION = ...

# ==========================
# CONFIGURACIÓN DEL ETL
# ==========================

SUPPORTED_EXTENSIONS = ...
REQUIRED_COLUMNS = ...
NULL_VALUES = ...
DATE_FORMAT = ...

# ==========================
# CONFIGURACIÓN DE LOS KPIs
# ==========================

ABC_PERCENTAGES = ...
TOP_ITEMS = ...
OBSOLESCENCE_MONTHS = ...
FORECAST_PERIODS = ...